name: Auto-merge main into release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  merge-to-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for full history

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into release
        run: |
          git checkout release
          git pull origin release
          git merge origin/main --no-edit || (echo "Merge conflict detected"; exit 1)
          git push origin release
