name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: your.server.com
          username: youruser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/es1tp"
